package com.weather;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "Weather")
@DynamoDBDocument
public class City {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String Location;

    @DynamoDBAttribute
    private String temp;

    @DynamoDBAttribute
    private String main;

    @DynamoDBAttribute
    private String temp_min;

    @DynamoDBAttribute
    private String temp_max;

}
